### ISSUE TITLE
Query regarding SEO: Site not showing up on searches

### ISSUE THREAD

**Issue by turzobose** [zerostaticthemes/jekyll-serif-theme#40]
Thanks a lot for such a beautiful and clean design. I have added the meta descriptions and other details needed for the SEO. However, even after 2 days of publishing the website, I do not see the website appearing when I search it on google or safari. I have gone further and added meta keywords to the index.md and subsequently to default.html. I researched online for SEO with Jekyll and see that jekyll-seo-plugin is very popular amongst jekyll developers. But, I do not see that plugin being called in the GEM file or config.yaml. If not a particular plugin, how does the seo of this template navigate? I am a beginner and still very much in the learning process, so apologies if the query is quite obvious/basic. Thank you in advance for your help.

**Comment by billsmithsmithbill22** [comment]
Hello,
You need to submit your site to google. Otherwise, you just need to wait until one of their bots crawl your site. If SEO isn't that important, this is all you probably need. Additionally, unless you search very specifically (using site:), you probably aren't going to see it for a bunch of pages. Hope this helps. 
[https://search.google.com/search-console/welcome](url)

Additionally, this might have been a better question for the Jekyll forums: 
[https://talk.jekyllrb.com/](url)

Good Luck!

**Comment by JugglerX** [comment]
This theme has good SEO. Not every website will rank after 2 days. Hope things improved for you!
