### ISSUE TITLE
adding jekyll-seo-tag and other minor issues

### ISSUE THREAD

**Issue by aamirv** [zerostaticthemes/jekyll-serif-theme#73]
Hi - thank you for building this.  I took the repo and made a few changes for my own site.  I'm wondering if something like incorporating the jekyll-seo-tag (so it handles all the title/description) stuff would be useful.  It's very easy, but I'm not sure if it's something you'd like to see in the project.

**Comment by peter1357908** [comment]
I tried to do the same and found out that `jekyll-seo-tag` expects `logo` in `_config.yml` to be just a string instead of a hashmap like it currently is. Refactoring is needed to make the responsive logo work alongside `jekyll-seo-tag`.

On the other hand, there are already some "hard-coded" seo tags in `default.html`.

**Comment by JugglerX** [comment]
You dont need that plugin. It's easier to just extend your own partial to handle basic SEO stuff. feel free to do a PR extending what we already have.
